# This pipeline builds and pushes multiple container images to Azure Container Registry (ACR)
# and deploys them to an Azure Linux App Service as sidecar containers.

# Structure of the sample project, where router-app works like main container and hello-app is the sidecar container:
# - router-app/  
#   - requirements.txt
#   - app.py
#   - Dockerfile
# - hello-app/  
#   - Dockerfile
#   - app.py
#   - requirements.txt

trigger:
  branches:
    include:
      - test/sitecontainer   # replace with your branch name to trigger the pipeline

variables:
  dockerRegistryServiceConnection: 'sitecontainersampleacr-sc' # replace with your ACR service connection name
  containerRegistry: 'sitecontainerssampleacr.azurecr.io'      # replace with your Container Registry login server
  routerAppImageName: 'test/router-app'                        # router app image name in Container Registry
  helloAppImageName: 'test/hello-app'                          # hello app image name in Container Registry
  azureSubscription: 'sitecontainers-sc'                       # replace with your Azure RM connection name
  appName: 'vsts-docker2'                                      # your App Service name
  resourceGroup: 'multicontainer-euap'                         # your App Service's resource group
  projectRoot: 'LinuxAppService/SiteContainers/test/samples'   # your project root folder

pool:
  vmImage: 'ubuntu-latest'

steps:
  # one by one specify steps to build and push each container image to Container Registry
- task: Docker@2
  displayName: 'Build and Push Docker router-app Image to Container Registry'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(routerAppImageName)
    command: buildAndPush
    Dockerfile: '$(projectRoot)/router-app/Dockerfile'
    buildContext: '$(projectRoot)/router-app'
    tags: |
      $(Build.BuildId)

- task: Docker@2
  displayName: 'Build and Push Docker hello app Image to Container Registry'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(helloAppImageName)
    command: buildAndPush
    Dockerfile: '$(projectRoot)/hello-app/Dockerfile'
    buildContext: '$(projectRoot)/hello-app'
    tags: |
      $(Build.BuildId)

# Deployment step to deploy both main and sidecar containers to Azure Linux App Service
- task: AzureWebAppContainer@1
  displayName: 'Deploy to Linux App Service'
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    resourceGroupName: $(resourceGroup)
    # sitecontainersConfig property to define all containers in the App Service
    sitecontainersConfig: |
      [
        {
          "name": "main",
          "image": "$(containerRegistry)/$(routerAppImageName):$(Build.BuildId)",
          "targetPort": 5000,
          "isMain": true
        },
        {
          "name": "hello-app",
          "image": "$(containerRegistry)/$(helloAppImageName):$(Build.BuildId)",
          "targetPort": 5001,
          "isMain": false
        }
      ]

# Following properties can be set for each container in the sitecontainers-config list.
# SiteContainer 
# {
#     name: string, // mandatory
#     image: string, // mandatory
#     isMain: boolean, // mandatory
#     targetPort?: string,
#     startupCommand?: string,
#     authType?: AUTH_TYPE,
#     userName?: string,
#     passwordSecret?: string,
#     userManagedIdentityClientId?: string,
#     environmentVariables?: EnvironmentVariable[],
#     volumeMounts?: VolumeMount[],
#     inheritAppSettingsAndConnectionStrings?: boolean,
#   }

# AUTH_TYPE is any of the following:
#   Anonymous,
#   UserCredentials,
#   SystemIdentity,
#   UserAssigned

# type EnvironmentVariable {
#   name: string; // mandatory
#   value: string; // mandatory
# }
# type VolumeMount {
#     name: string; // mandatory
#     mountPath: string; // mandatory
#     readOnly?: boolean;
# }